### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by NeoPlayer13** [LevantinLynx/gotify-to-ntfy-proxy#1]
I'm using a selfhosted ntfy server. For ease of use I'm running the proxy in the same docker network as the ntfy server, so I can resolve by container_name.  I'm using an already tested token since I'm reusing for testing purpose the token of another application that been working for months.

### **ERROR:**
```
ERROR: could not notify via target `pve-gotify-to-ntfy-proxy`: could not notify via endpoint(s): pve-gotify-to-ntfy-proxy: http://192.168.1.180:8086/message: Connection Failed: Connect error: Connection refused (os error 111)
``` 
### Configuration: * 
```
version: "2.1"
services:
  gotify-to-ntfy-proxy:
    image: 'levantinlynx/gotify-to-ntfy-proxy:latest'
    restart: unless-stopped
    volumes:
      - '/docker/ntfy/proxy/topics.js:/home/node/app/topics.js'
    ports:
      - '8086:8008'
    environment:
      - RELAY_HOST_IP=0.0.0.0
      - RELAY_PORT=8086
      - NTFY_SERVER=ntfy
```

```javascript
const topics = {
    Reports: {
      ntfyToken: 'tk_mytoken'
    },
  }
  
  module.exports = topics
``` 

![image](https://github.com/LevantinLynx/gotify-to-ntfy-proxy/assets/98669870/7f7fb022-0007-4643-9ded-b71355b4aa39)

**Comment by LevantinLynx** [comment]
Hey there,

looks like you changed the RELAY_PORT but are exposing the original one.

Either leave the RELAY_PORT on 8008 or change the exposed ports to
```yaml
ports:
      - '8086:8086'
```
and it should work.

**Comment by NeoPlayer13** [comment]
I already tried both options, the original port and the modified port, but it returns this error:
```
Could not test target: could not notify via endpoint(s): pve-gotify-to-ntfy-proxy: http://192.168.1.180:8086/message: Network Error: Unexpected EOF (500)
```
or 
```
Could not test target: could not notify via endpoint(s): pve-gotify-to-ntfy-proxy: http://192.168.1.180:8008/message: Network Error: Unexpected EOF (500)
```

**Comment by LevantinLynx** [comment]
Took me quite some time to figure out that you removed the "http://" protocol part from the NTFY_SERVER variable :upside_down_face:

### Your config with my fixes

Assuming your ntfy container is in the same network as the gotify-to-ntfy-proxy container and is actually called "ntfy", the following config should work.

```yaml
version: "2.1"
services:
  gotify-to-ntfy-proxy:
    image: 'levantinlynx/gotify-to-ntfy-proxy:latest'
    restart: unless-stopped
    volumes:
      - '/docker/ntfy/proxy/topics.js:/home/node/app/topics.js'
    ports:
      - '8086:8008'
    environment:
      - RELAY_HOST_IP=0.0.0.0
      - RELAY_PORT=8008
      - NTFY_SERVER=http://ntfy
```

### Working config tested on my end
Since Traefik proxy is using port 80 on my Docker host i used 8080 for the ntfy container. Since we are testing docker internal routing that does not matter tho. I tested it with this exact config and got the notification on my phone.

```yaml
version: '3.9'
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    volumes:
      - /home/lev/stacks/gotify-to-ntfy/ntfy-cache:/var/cache/ntfy
      - /home/lev/stacks/gotify-to-ntfy/ntfy-etc:/etc/ntfy
    ports:
      - 80:80
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  gotify-to-ntfy-proxy:
    image: 'levantinlynx/gotify-to-ntfy-proxy:latest'
    restart: unless-stopped
    volumes:
      - '/home/lev/stacks/gotify-to-ntfy/topics.js:/home/node/app/topics.js'
    ports:
      - '8086:8008'
    environment:
      - NODE_ENV=production
      - RELAY_HOST_IP=0.0.0.0
      - RELAY_PORT=8008
      - NTFY_SERVER=http://ntfy
``` 
![docker-test](https://github.com/LevantinLynx/gotify-to-ntfy-proxy/assets/16870542/3b5fbb38-1ba6-4110-9c48-7f46d2f9afe5)
![0bafabec](https://github.com/LevantinLynx/gotify-to-ntfy-proxy/assets/16870542/d789d994-ae08-4bf3-8456-4661d603e5c7)
![3819238e](https://github.com/LevantinLynx/gotify-to-ntfy-proxy/assets/16870542/01d659c4-4fd7-4583-963d-bee73cd64bb4)
